"""empty message

Revision ID: 4a2db5ac1456
Revises: f6e6ee7e681c
Create Date: 2016-04-06 22:09:46.042000

"""

# revision identifiers, used by Alembic.
revision = '4a2db5ac1456'
down_revision = 'f6e6ee7e681c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incentives',
    sa.Column('incentive_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('cutoff_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('incentive_id')
    )
    op.create_table('donations',
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('incentive_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incentive_id'], ['incentives.incentive_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donations')
    op.drop_table('incentives')
    ### end Alembic commands ###
