"""empty message

Revision ID: 54b9bc49716f
Revises: 4a2db5ac1456
Create Date: 2016-04-07 00:46:12.480000

"""

# revision identifiers, used by Alembic.
revision = '54b9bc49716f'
down_revision = '4a2db5ac1456'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipns',
    sa.Column('ipn_id', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('address_status', sa.String(length=50), nullable=True),
    sa.Column('payer_status', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('payer_email', sa.String(length=255), nullable=True),
    sa.Column('payer_id', sa.String(length=255), nullable=True),
    sa.Column('address_country', sa.String(length=100), nullable=True),
    sa.Column('business', sa.String(length=255), nullable=True),
    sa.Column('receiver_email', sa.String(length=255), nullable=True),
    sa.Column('receiver_id', sa.String(length=255), nullable=True),
    sa.Column('mc_currency', sa.String(length=10), nullable=True),
    sa.Column('mc_fee', sa.String(length=20), nullable=True),
    sa.Column('mc_gross', sa.String(length=20), nullable=True),
    sa.Column('txn_type', sa.String(length=20), nullable=True),
    sa.Column('txn_id', sa.String(length=20), nullable=True),
    sa.Column('custom', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ipn_id')
    )
    with op.batch_alter_table(u'donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ipn_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_donations_ipn_id_ipns', 'ipns', ['ipn_id'], ['ipn_id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'donations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donations_ipn_id_ipns', type_='foreignkey')
        batch_op.drop_column('ipn_id')
        batch_op.drop_column('first_name')
        batch_op.drop_column('country')

    op.drop_table('ipns')
    ### end Alembic commands ###
