"""empty message

Revision ID: 624bc57aed38
Revises: 54b9bc49716f
Create Date: 2016-04-07 01:17:31.936000

"""

# revision identifiers, used by Alembic.
revision = '624bc57aed38'
down_revision = '54b9bc49716f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_hash'), ['hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_donations_status'), ['status'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_status'))
        batch_op.drop_index(batch_op.f('ix_donations_hash'))

    ### end Alembic commands ###
