"""empty message

Revision ID: 8c8f5fd221f7
Revises: 624bc57aed38
Create Date: 2016-04-07 12:12:40.973000

"""

# revision identifiers, used by Alembic.
revision = '8c8f5fd221f7'
down_revision = '624bc57aed38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('paypal_email', sa.String(length=255), nullable=True),
    sa.Column('paypal_sandbox', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    ### end Alembic commands ###
